---
server_install_dir: /opt/cloudlaunch-server
server_venv: "{{ server_install_dir }}/.venv"
ui_install_dir: /opt/cloudlaunch-ui
log_dir: /var/log/cloudlaunch/
system_user: cloudlaunch
system_group: cloudlaunch

broker_user: cloudlaunch
broker_pwd: "BROKERPWDTOCHANGE"
task_time_limit: 4000

dbuser: cloudlaunch
dbname: cloudlaunch
dbpassword: "CHANGEMEONINSTALL"

server_name: beta.launch.usegalaxy.org
ssl_cert_path: /etc/nginx/ssl/cl.crt
ssl_key_path: /etc/nginx/ssl/cl.key
ssl_cert_files:  # These files need to be placed into files/secret and vaulted
  - beta.launch.usegalaxy.org_certchain.pem
  - cl.crt
  - cl.key
...
