- name: Install supervisor package
  apt: name={{ item }} state=latest
  with_items:
   - supervisor

- name: Make sure supervisor is running
  service: name=supervisor state=started
  
- name: Create the Supervisor config file
  template: src=supervisor_config_cloudlaunch.j2
            dest=/etc/supervisor/conf.d/cloudlaunch.conf

- name: Re-read the Supervisor config files
  supervisorctl: name={{ item }} state=present
  with_items:
    - celeryd
    - cloudlaunch

- name: Restart the Supervisor services
  supervisorctl: name={{ item }} state=restarted
  with_items:
    - celeryd
    - cloudlaunch
