---
- name: Install Postgres package
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
   - postgresql
   - postgresql-contrib

- name: Start Postgres service
  service:
    name: postgresql
    state: started
    enabled: true
...
