- name: Add latest Python and Ansible PPAs
  apt_repository: repo={{ item }} update_cache=no
  with_items:
    - ppa:fkrull/deadsnakes
    - ppa:ansible/ansible

- name: Update APT cache
  apt: update_cache=yes

- name: Install setuptools
  apt: pkg={{ item }} state=latest install_recommends=no force=yes
  with_items:
    - python-setuptools
    - python-dev
    - python-pip

- name: Install Python packages for SSL cert verification
  pip:
    name: "{{ item }}"
  with_items:
    - urllib3
    - pyopenssl
    - ndg-httpsclient
    - pyasn1

- name: Add NodeSource repository for Node.js 6.0
  apt_repository: repo='{{ item }} https://deb.nodesource.com/node_6.x {{ ansible_distribution_release|lower }} main' state=present update_cache=no
  with_items:
    - deb
    - deb-src

- name: Add NodeSource apt key
  apt_key:
    id: 68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Update APT cache
  apt: update_cache=yes

- name: Install system packages
  apt: pkg={{ item }} state=latest install_recommends=no force=yes
  with_items:
    - ansible
    - gcc
    - git-core
    - libffi-dev
    - libncurses5-dev
    - libssl-dev
    - nodejs
    - python3.5
    - python3.5-dev
    - python3-pip
    - python3.5-venv
    - python-virtualenv
    - python3-setuptools
    - python-dev
    - python3-dev
    - libpq-dev         # For postgres psycopg2 compilation
    - python-psycopg2   # For postgres psycopg2 compilation
    - software-properties-common
    - wget
    - vim

- name: Install global npm packages
  npm: name={{ item }} global=yes
  with_items:
    - tsd
    - typings

- name: Update python-setuptools
  pip: name=setuptools state=latest executable=pip3

- name: Install nginx
  apt: name={{ item }} state=latest
  with_items:
   - nginx

- name: Remove default nginx site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
   - reload nginx

- name: Start the nginx service
  service: name=nginx state=started enabled=yes
